# Generated by Django 4.2.6 on 2023-10-09 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='post',
            new_name='post_publish_49d927_idx',
            old_name='blog_post_publish_bb7600_idx',
        ),
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
    ]
