# Generated by Django 4.2.6 on 2023-10-09 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_blog_post_publish_bb7600_idx_post_publish_49d927_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish',), 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
